name: Example - Build ESP8266 Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build with action
        uses: jackestar/esp8266-rtos-sdk-action@V0
        with:
          install-deps: 'true'

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin
